#pragma once

#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "intrinsic/thread/thread.hpp"
#include "intrinsic/hal/hardware_module_interface.hpp"
#include "intrinsic/hal/hardware_interface_handle.hpp"
#include "intrinsic/shared_memory_manager/domain_socket_server.hpp"
#include "intrinsic/shared_memory_manager/shared_memory_manager.hpp"

// Generated by flatc
#include "hwm_fbs/icon_state.fbs.h"
#include "hwm_fbs/joint_state.fbs.h"
#include "hwm_fbs/joint_command.fbs.h"
#include "hwm_fbs/hardware_module_state.fbs.h"

#include "intrinsic/hal/realtime_clock.hpp"
#include "intrinsic/shared_memory_manager/remote_trigger_server.hpp"
#include "intrinsic/shared_memory_manager/shared_memory_lockstep.hpp"

#include "controller_manager_msgs/srv/set_hardware_component_state.hpp"
#include "controller_manager_msgs/srv/switch_controller.hpp"

// Generated by generate_parameter_library
#include "icon_hwm_controller/icon_hwm_controller_parameters.hpp"

namespace icon_hwm_controller {

class IconHwmController final : public controller_interface::ControllerInterface,
                                public intrinsic::hal::HardwareModuleInterface {
 public:
  IconHwmController() = default;

  // controller_interface::ControllerInterface
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;

  // intrinsic::hal::HardwareModuleInterface
  intrinsic::Status Init() override { return intrinsic::OkStatus(); }
  intrinsic::Status Prepare() override;
  intrinsic::RealtimeStatus Activate() override;
  intrinsic::RealtimeStatus Deactivate() override;
  intrinsic::Status EnableMotion() override;
  intrinsic::Status DisableMotion() override;
  intrinsic::Status ClearFaults() override;
  intrinsic::Status Shutdown() override;
  intrinsic::RealtimeStatus ReadStatus() override;
  intrinsic::RealtimeStatus ApplyCommand() override;

 private:
  // Parameters
  std::unique_ptr<ParamListener> param_listener_;
  Params params_;

  // Shared Memory
  std::unique_ptr<intrinsic::hal::SharedMemoryManager> shm_manager_;
  std::unique_ptr<intrinsic::hal::DomainSocketServer> domain_socket_server_;
  intrinsic::hal::HardwareInterfaceHandle<intrinsic_fbs::IconState> icon_state_;
  intrinsic::hal::MutableStrictHardwareInterfaceHandle<intrinsic_fbs::JointPositionState> joint_position_state_;
  intrinsic::hal::MutableStrictHardwareInterfaceHandle<intrinsic_fbs::JointVelocityState> joint_velocity_state_;
  intrinsic::hal::StrictHardwareInterfaceHandle<intrinsic_fbs::JointPositionCommand> joint_position_command_;
  intrinsic::hal::MutableHardwareInterfaceHandle<intrinsic_fbs::HardwareModuleState> hardware_module_state_;

  // Remote Trigger Servers
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> prepare_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> activate_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> deactivate_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> enable_motion_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> disable_motion_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> clear_faults_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> shutdown_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> read_status_server_;
  std::unique_ptr<intrinsic::hal::RemoteTriggerServer> apply_command_server_;

  intrinsic::Thread state_change_query_thread_;

  // Clock Driver
  std::unique_ptr<intrinsic::RealtimeClock> clock_;

  // Service Clients
  rclcpp::Client<controller_manager_msgs::srv::SwitchController>::SharedPtr switch_controller_client_;
  rclcpp::Client<controller_manager_msgs::srv::SetHardwareComponentState>::SharedPtr set_hw_state_client_;

  // Internal state
  uint64_t cycle_counter_ = 0;
  std::atomic<intrinsic_fbs::StateCode> state_code_{intrinsic_fbs::StateCode::kDeactivated};
  std::atomic<bool> stop_requested_{false};
  std::string fault_reason_;
  bool faulted_ = false;

  // Helper methods
  void DetectFaults();
  void UpdateHwmState();
  bool SetStateDirectly(intrinsic_fbs::StateCode state, std::string_view fault_reason = "", bool force = false, bool silent = false);
  intrinsic::Status CallSwitchController(const std::vector<std::string>& activate, const std::vector<std::string>& deactivate);
  intrinsic::Status CallSetHwState(const std::string& name, uint8_t state);
};

}
