FROM ros:jazzy-ros-core
RUN apt-get update && apt-get install -y ros-jazzy-xacro ros-jazzy-backward-ros python3-filelock ros-jazzy-ros2-control ros-jazzy-ros2-controllers ros-jazzy-robot-state-publisher && rm -rf /var/lib/apt/lists/*
ENV HOME=/tmp
