# proto-file: flowstate_ros_bridge.proto
# proto-message: FlowstateRosBridgeConfig
# Corresponds to the message definition in flowstate_ros_bridge.proto
[type.googleapis.com/intrinsic.FlowstateRosBridgeConfig] {
  workcell_id: ""
  executive_service_address: "executive.app-intrinsic-app-chart.svc.cluster.local:8080"
  skill_registry_address: "skill-registry.app-intrinsic-app-chart.svc.cluster.local:8080"
  solution_service_address: "frontend.app-intrinsic-base.svc.cluster.local:8082"
  world_service_address: "world.app-intrinsic-base.svc.cluster.local:8080"
  geometry_service_address: "geomservice.app-intrinsic-base.svc.cluster.local:8080"
  flowstate_zenoh_router_address: "tcp/zenoh-router.app-intrinsic-base:7447"
  external_zenoh_router_address: "tcp/zenoh-router.app-intrinsic-base:7447"
  bridge_plugins: [
    "flowstate_ros_bridge::WorldBridge",
    "flowstate_ros_bridge::ExecutiveBridge",
    "flowstate_ros_bridge::DiagnosticsBridge"
  ],
  executive_deadline_seconds: 5
  executive_update_rate_millis: 1000
  diagnostics_service_address: "istio-ingressgateway.app-ingress.svc.cluster.local:80"
  diagnostics_deadline_seconds: 5
  sensors {
    enable_joint_states: true
    enable_gripper_states: true
    enable_force_torque: false
    enable_camera_stream: false
  }
}
