// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HARDWAREMODULESTATE_INTRINSIC_FBS_H_
#define FLATBUFFERS_GENERATED_HARDWAREMODULESTATE_INTRINSIC_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace intrinsic_fbs {

struct HardwareModuleState;

enum TransitionRequest : uint8_t {
  TransitionRequest_kActivate = 0,
  TransitionRequest_kDeactivate = 1,
  TransitionRequest_kEnableMotion = 2,
  TransitionRequest_kDisableMotion = 3,
  TransitionRequest_kClearFaults = 4,
  TransitionRequest_kPrepare = 5,
  TransitionRequest_MIN = TransitionRequest_kActivate,
  TransitionRequest_MAX = TransitionRequest_kPrepare
};

inline const TransitionRequest (&EnumValuesTransitionRequest())[6] {
  static const TransitionRequest values[] = {
    TransitionRequest_kActivate,
    TransitionRequest_kDeactivate,
    TransitionRequest_kEnableMotion,
    TransitionRequest_kDisableMotion,
    TransitionRequest_kClearFaults,
    TransitionRequest_kPrepare
  };
  return values;
}

inline const char * const *EnumNamesTransitionRequest() {
  static const char * const names[7] = {
    "kActivate",
    "kDeactivate",
    "kEnableMotion",
    "kDisableMotion",
    "kClearFaults",
    "kPrepare",
    nullptr
  };
  return names;
}

inline const char *EnumNameTransitionRequest(TransitionRequest e) {
  if (flatbuffers::IsOutRange(e, TransitionRequest_kActivate, TransitionRequest_kPrepare)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTransitionRequest()[index];
}

enum StateCode : uint8_t {
  StateCode_kDeactivated = 0,
  StateCode_kDeactivating = 1,
  StateCode_kActivated = 2,
  StateCode_kActivating = 3,
  StateCode_kMotionEnabled = 4,
  StateCode_kMotionEnabling = 5,
  StateCode_kMotionDisabling = 6,
  StateCode_kFaulted = 7,
  StateCode_kClearingFaults = 8,
  StateCode_kInitFailed = 9,
  StateCode_kFatallyFaulted = 10,
  StateCode_kPreparing = 11,
  StateCode_kPrepared = 12,
  StateCode_MIN = StateCode_kDeactivated,
  StateCode_MAX = StateCode_kPrepared
};

inline const StateCode (&EnumValuesStateCode())[13] {
  static const StateCode values[] = {
    StateCode_kDeactivated,
    StateCode_kDeactivating,
    StateCode_kActivated,
    StateCode_kActivating,
    StateCode_kMotionEnabled,
    StateCode_kMotionEnabling,
    StateCode_kMotionDisabling,
    StateCode_kFaulted,
    StateCode_kClearingFaults,
    StateCode_kInitFailed,
    StateCode_kFatallyFaulted,
    StateCode_kPreparing,
    StateCode_kPrepared
  };
  return values;
}

inline const char * const *EnumNamesStateCode() {
  static const char * const names[14] = {
    "kDeactivated",
    "kDeactivating",
    "kActivated",
    "kActivating",
    "kMotionEnabled",
    "kMotionEnabling",
    "kMotionDisabling",
    "kFaulted",
    "kClearingFaults",
    "kInitFailed",
    "kFatallyFaulted",
    "kPreparing",
    "kPrepared",
    nullptr
  };
  return names;
}

inline const char *EnumNameStateCode(StateCode e) {
  if (flatbuffers::IsOutRange(e, StateCode_kDeactivated, StateCode_kPrepared)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStateCode()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) HardwareModuleState FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t code_;
  uint8_t message_[256];

 public:
  HardwareModuleState()
      : code_(0),
        message_() {
  }
  HardwareModuleState(intrinsic_fbs::StateCode _code)
      : code_(flatbuffers::EndianScalar(static_cast<uint8_t>(_code))),
        message_() {
  }
  HardwareModuleState(intrinsic_fbs::StateCode _code, flatbuffers::span<const uint8_t, 256> _message)
      : code_(flatbuffers::EndianScalar(static_cast<uint8_t>(_code))) {
    flatbuffers::CastToArray(message_).CopyFromSpan(_message);
  }
  intrinsic_fbs::StateCode code() const {
    return static_cast<intrinsic_fbs::StateCode>(flatbuffers::EndianScalar(code_));
  }
  const flatbuffers::Array<uint8_t, 256> *message() const {
    return &flatbuffers::CastToArray(message_);
  }
};
FLATBUFFERS_STRUCT_END(HardwareModuleState, 257);

}  // namespace intrinsic_fbs

#endif  // FLATBUFFERS_GENERATED_HARDWAREMODULESTATE_INTRINSIC_FBS_H_
