// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRANSFORMTYPES_INTRINSIC_FBS_H_
#define FLATBUFFERS_GENERATED_TRANSFORMTYPES_INTRINSIC_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace intrinsic_fbs {

struct Point;

struct Rotation;

struct Twist;

struct Acceleration;

struct Jerk;

struct Wrench;

struct Transform;

struct VectorNd;
struct VectorNdBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Point FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;

 public:
  Point()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Point(double _x, double _y, double _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  double x() const {
    return flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Point, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Rotation FLATBUFFERS_FINAL_CLASS {
 private:
  double qx_;
  double qy_;
  double qz_;
  double qw_;

 public:
  Rotation()
      : qx_(0),
        qy_(0),
        qz_(0),
        qw_(0) {
  }
  Rotation(double _qx, double _qy, double _qz, double _qw)
      : qx_(flatbuffers::EndianScalar(_qx)),
        qy_(flatbuffers::EndianScalar(_qy)),
        qz_(flatbuffers::EndianScalar(_qz)),
        qw_(flatbuffers::EndianScalar(_qw)) {
  }
  double qx() const {
    return flatbuffers::EndianScalar(qx_);
  }
  double qy() const {
    return flatbuffers::EndianScalar(qy_);
  }
  double qz() const {
    return flatbuffers::EndianScalar(qz_);
  }
  double qw() const {
    return flatbuffers::EndianScalar(qw_);
  }
};
FLATBUFFERS_STRUCT_END(Rotation, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Twist FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;
  double rx_;
  double ry_;
  double rz_;

 public:
  Twist()
      : x_(0),
        y_(0),
        z_(0),
        rx_(0),
        ry_(0),
        rz_(0) {
  }
  Twist(double _x, double _y, double _z, double _rx, double _ry, double _rz)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        rx_(flatbuffers::EndianScalar(_rx)),
        ry_(flatbuffers::EndianScalar(_ry)),
        rz_(flatbuffers::EndianScalar(_rz)) {
  }
  double x() const {
    return flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return flatbuffers::EndianScalar(z_);
  }
  double rx() const {
    return flatbuffers::EndianScalar(rx_);
  }
  double ry() const {
    return flatbuffers::EndianScalar(ry_);
  }
  double rz() const {
    return flatbuffers::EndianScalar(rz_);
  }
};
FLATBUFFERS_STRUCT_END(Twist, 48);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Acceleration FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;
  double rx_;
  double ry_;
  double rz_;

 public:
  Acceleration()
      : x_(0),
        y_(0),
        z_(0),
        rx_(0),
        ry_(0),
        rz_(0) {
  }
  Acceleration(double _x, double _y, double _z, double _rx, double _ry, double _rz)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        rx_(flatbuffers::EndianScalar(_rx)),
        ry_(flatbuffers::EndianScalar(_ry)),
        rz_(flatbuffers::EndianScalar(_rz)) {
  }
  double x() const {
    return flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return flatbuffers::EndianScalar(z_);
  }
  double rx() const {
    return flatbuffers::EndianScalar(rx_);
  }
  double ry() const {
    return flatbuffers::EndianScalar(ry_);
  }
  double rz() const {
    return flatbuffers::EndianScalar(rz_);
  }
};
FLATBUFFERS_STRUCT_END(Acceleration, 48);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Jerk FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;
  double rx_;
  double ry_;
  double rz_;

 public:
  Jerk()
      : x_(0),
        y_(0),
        z_(0),
        rx_(0),
        ry_(0),
        rz_(0) {
  }
  Jerk(double _x, double _y, double _z, double _rx, double _ry, double _rz)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        rx_(flatbuffers::EndianScalar(_rx)),
        ry_(flatbuffers::EndianScalar(_ry)),
        rz_(flatbuffers::EndianScalar(_rz)) {
  }
  double x() const {
    return flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return flatbuffers::EndianScalar(z_);
  }
  double rx() const {
    return flatbuffers::EndianScalar(rx_);
  }
  double ry() const {
    return flatbuffers::EndianScalar(ry_);
  }
  double rz() const {
    return flatbuffers::EndianScalar(rz_);
  }
};
FLATBUFFERS_STRUCT_END(Jerk, 48);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Wrench FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;
  double rx_;
  double ry_;
  double rz_;

 public:
  Wrench()
      : x_(0),
        y_(0),
        z_(0),
        rx_(0),
        ry_(0),
        rz_(0) {
  }
  Wrench(double _x, double _y, double _z, double _rx, double _ry, double _rz)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        rx_(flatbuffers::EndianScalar(_rx)),
        ry_(flatbuffers::EndianScalar(_ry)),
        rz_(flatbuffers::EndianScalar(_rz)) {
  }
  double x() const {
    return flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return flatbuffers::EndianScalar(z_);
  }
  double rx() const {
    return flatbuffers::EndianScalar(rx_);
  }
  double ry() const {
    return flatbuffers::EndianScalar(ry_);
  }
  double rz() const {
    return flatbuffers::EndianScalar(rz_);
  }
};
FLATBUFFERS_STRUCT_END(Wrench, 48);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Transform FLATBUFFERS_FINAL_CLASS {
 private:
  intrinsic_fbs::Point position_;
  intrinsic_fbs::Rotation rotation_;

 public:
  Transform()
      : position_(),
        rotation_() {
  }
  Transform(const intrinsic_fbs::Point &_position, const intrinsic_fbs::Rotation &_rotation)
      : position_(_position),
        rotation_(_rotation) {
  }
  const intrinsic_fbs::Point &position() const {
    return position_;
  }
  const intrinsic_fbs::Rotation &rotation() const {
    return rotation_;
  }
};
FLATBUFFERS_STRUCT_END(Transform, 56);

struct VectorNd FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VectorNdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const flatbuffers::Vector<double> *data() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct VectorNdBuilder {
  typedef VectorNd Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(flatbuffers::Offset<flatbuffers::Vector<double>> data) {
    fbb_.AddOffset(VectorNd::VT_DATA, data);
  }
  explicit VectorNdBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<VectorNd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VectorNd>(end);
    return o;
  }
};

inline flatbuffers::Offset<VectorNd> CreateVectorNd(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<double>> data = 0) {
  VectorNdBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline flatbuffers::Offset<VectorNd> CreateVectorNdDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<double>(*data) : 0;
  return intrinsic_fbs::CreateVectorNd(
      _fbb,
      data__);
}

}  // namespace intrinsic_fbs

#endif  // FLATBUFFERS_GENERATED_TRANSFORMTYPES_INTRINSIC_FBS_H_
