find_package(flatbuffers_vendor REQUIRED)
find_package(tl_expected_vendor REQUIRED)
find_package(eigen_vendor REQUIRED)

find_package(flatbuffers REQUIRED)
find_package(tl-expected REQUIRED)
find_package(Eigen3 REQUIRED)

find_package(controller_interface REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
find_package(realtime_tools REQUIRED)
find_package(std_msgs REQUIRED)
find_package(generate_parameter_library REQUIRED)
