# Request

# The behavior tree to run on Flowstate.
BehaviorTree behavior_tree

# The execution mode.
ExecutionMode execution_mode

# The simulation mode
SimulationMode simulation_mode

# JSON parameters for the behavior_tree serialized as a string.
string parameters

# [OPTIONAL] The scene ID to be associated with this operation.
# This specifies the starting state for the world in which this operation
# will run. If this value is not set, the operation will run in the world in
# its current state.
# Note: To reset to the initial world, set scene_id to "init_world".
string scene_id

---

# Response
# True if the process executed successfully.
bool success

# [OPTIONAL] message for debugging or indicating cause of success/failure
string message

# Result of the task
string result

---

# Feedback
bool done

string error_message
