# proto-file: google/protobuf/any.proto
# proto-message: Any
[type.googleapis.com/flowstate.RosGzBridgeConfig] {
  bridges {
    ros_topic_name: "/clock"
    gz_topic_name: "/clock"
    ros_type_name: "rosgraph_msgs/msg/Clock"
    gz_type_name: "gz.msgs.Clock"
    lazy: false
    direction: GZ_TO_ROS
    qos_profile: CLOCK
  }
}
