name: Sync Embedded Requirements

on:
  pull_request:
    paths:
      - 'resources/pip_requirements/requirements.txt'

jobs:
  sync-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # was: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.12'

      - name: Run sync script
        run: ./resources/pip_requirements/sync_requirements.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403  # v5.2.0
        with:
          commit_message: "chore: sync embedded pip requirements in Dockerfiles"
          file_pattern: 'resources/Dockerfile.skill intrinsic_sdk_bundle_library_py/resource/skill.Dockerfile'
